### PR TITLE
Add basic tests for InteractionTask

### PR DESCRIPTION
**Pull request by christophajohns**
I have created an extremely basic testing module for the `InteractionTask` class that just checks for some expected properties and methods. I'll create a draft PR for this, because I could use some feedback whether there are some additional requirements for the `InteractionTask` that should be tested.

### CODE REVIEW

**Comment by christophajohns** [comment]
Oh, and also I installed black as a dev dependency and upgraded scipy to 1.7.3 since I could not get the package running otherwise using poetry.

**Comment by jgori-ouistiti** [comment]
The first thing that comes to mind that is missing is to verify the forced-reset mechanism. When you reset a bundle, you can pass it a reset_dictionnary {'task_state': task_reset_dic, 'user_state': user_reset_dic, etc.}. The value associated with the task_state key is passed to _base_reset as dic. A couple things to check here are that without dic provided, the state is randomly reset (maybe check by fixing the seed of the stateElements), with dic provided the reset is correctly achieved to the forced state in input, and in between (if the reset_dic specifies a value for x_1 but not x_2, x_2 should be reset randomly)

**Comment by christophajohns** [comment]
Alright, I will give this a shot then

**Comment by jgori-ouistiti** [comment]
after that I suggest we stop there for this class, I'm pretty sure we are missing a thing or two, but for now we should try and cover most classes with the most important mechanisms, even if missing some cases. We can always add tests when we are debugging some behavior later on.

**Comment by christophajohns** [comment]
The signature for `InteractionTask.reset()` includes an argument for a `dic`. You mention that this is likely outdated. I would like to remove it, but that means that the task subclass definitions (e.g. in coopihczoo) that call `super().reset(dic=dic)` need to be updated. I think that is a good thing, but I need your opinion on this.

**Comment by christophajohns** [comment]
For now, I'll keep the `dic`, but I'll create an issue for this.

**Comment by jgori-ouistiti** [comment]
The reset() function is never called by the end-user; the end-user will call reset on Bundle, which will call the task's base reset with the relevant dic. 
The super().reset() calls should be removed in coopihczoo, because that mechanism has been replaced by the base_reset_mechanism. So it shouldn't be a problem. I'm updating coopihczoo at the moment actually, because many things are broken there; that is just one example. In general I would suggest that whenever you think there is some change that might break coopihczoo, please go ahead anyway, but file an issue in coopihczoo so that I am aware of it. Maybe you can create a special template for this type of issue if you think that is necessary, since these would be "expected bugs" rather than an actual bug.

**Comment by christophajohns** [comment]
Let's move this discussion to #44 then. Seems like a separate issue indeed.

**Comment by christophajohns** [comment]
As mentioned in PR #53, this PR suddenly had huge dependency conflicts. This PR will be removed and is replaced by PR #53.

**Pull request closed without merging**
