### PR TITLE
Add basic performance test for bundle round

### PR DESCRIPTION
**Pull request by christophajohns**
Using [pytest-benchmark](https://pytest-benchmark.readthedocs.io), I have added a very basic template to test the performance for a single bundle round. This can be used to start optimising the package's performance. To profile or measure performance changes, you can run, for example, `pytest test/integration/bundle/test_bundle_performance.py` which will display, among other things, the operations per second for the benchmarked tests. You can either use the autosave feature or manually save certain benchmarks using, for example, `pytest test/integration/bundle/test_bundle_performance.py --benchmark-save=bundle-round` to enable comparison using, for example, `pytest test/integration/bundle/test_bundle_performance.py --benchmark-compare`.

Related to issue #40.

### CODE REVIEW

**Comment by jgori-ouistiti** [comment]
See comment on #53 : can you have those changes on the function_switch_value branch?

**Comment by christophajohns** [comment]
I have changed the code to use the new StateElements. It took me quite some time to figure out the `self.state["x"][:] = …` API. That `[:]` was not exactly intuitive to me. The ExampleTask needed to be updated as well and the _Bundle.step() and InteractionTask._base_reset() needed some fixes too. Now, all tests in the test directory pass and the performance for one bundle round seems to have improved roughly 30%.

**Comment by christophajohns** [comment]
The Pull-Request-Checks seem to have failed. I'll look into that.

**Comment by christophajohns** [comment]
There still seems to be an issue with the PR checks. I'll look into it again and convert this PR into draft status until then.

**Comment by jgori-ouistiti** [comment]
> Edit: It seems that the VM does not have pytest-benchmark installed. Since it's already in the dev dependencies inside the TOML file, I'll just update the requirements file and try again.
> There still seems to be an issue with the PR checks. I'll look into it again and convert this PR into draft status until then.
Likely you need to update the  requirements.txt as well as the setup.py:
$ poetry export --without-hashes --dev -f requirements.txt --output requirements.txt
$ poetry build
then go to dist/ untar the tarball and copy paste the setup.py in the main repo.
It is a little ugly, but poetry does not have anything that automatically builds a setup, so you have to go get it from the target build. Maybe we should write a small makefile? And setup.py and requirements is required because the VM is setup to use pip

**Comment by jgori-ouistiti** [comment]
>  have changed the code to use the new StateElements. It took me quite some time to figure out the self.state["x"][:] = … API. That [:] was not exactly intuitive to me.

 self.state['x'] gets you the StateElement, which behaves like a Numpy Array.
The [:] is pretty standard Numpy indexing , it allows to change the values of the array in place. I need to doc this better I suppose

**Comment by jgori-ouistiti** [comment]
>  Now, all tests in the test directory pass and the performance for one bundle round seems to have improved roughly 30%.

There is an extra optimization possible, which would give a big performance boost --> StateElement in mode raw, which simply does not check that values belong to spaces. 
Also, the preprocessing of values is not optimized at all.
I haven't looked really into it, but we could also see if some functions can be JIT-compiled with Numba, since we are using numpy arrays now.
Another boost possible is to use tinyarray rather than numpy. tinyarray should have the same interface as numpy in theory, although may not have all features. But it is optimized for small arrays, whereas numpy excels at large arrays

**Comment by christophajohns** [comment]
> Likely you need to update the requirements.txt as well as the setup.py: $ poetry export --without-hashes --dev -f requirements.txt --output requirements.txt $ poetry build then go to dist/ untar the tarball and copy paste the setup.py in the main repo. It is a little ugly, but poetry does not have anything that automatically builds a setup, so you have to go get it from the target build. Maybe we should write a small makefile? And setup.py and requirements is required because the VM is setup to use pip

Yeah, just saw that too. That seems to have done the trick.

> self.state['x'] gets you the StateElement, which behaves like a Numpy Array. The [:] is pretty standard Numpy indexing , it allows to change the values of the array in place. I need to doc this better I suppose

Just chalk it up to me being a bit stubborn to embrace the change to use numpy under the hood then. Moving this PR to ready for review.

**Comment by christophajohns** [comment]
> There is an extra optimization possible, which would give a big performance boost --> StateElement in mode raw, which simply does not check that values belong to spaces. Also, the preprocessing of values is not optimized at all.

Yeah, the `StateElement._process_input_values` is still the biggest culprit for potentially lacking performance (ca. 50% of all time is spent in this function and it is called A LOT). This seems to be a reasonable starting point for performance improvements, both within the method itself and in the number of calls to it.

**Review by jgori-ouistiti — APPROVED** [review]

**Pull request merged**
